name: 'revizor'
description: 'revizor CLI'
inputs:
  command:
    description: 'Command to execute'
    required: true
  id:
    description: 'Container ID'
    required: false
outputs:
  id:
    description: 'Container ID'
  hostname:
    description: 'TE hostname'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.id }}
